/* tslint:disable */
/* eslint-disable */
/**
 * Product Partner API
 * Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.
 *
 * The version of the OpenAPI document: v1
 * Contact: info@productpartner.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

